language: python

python:
  - '3.7'

cache: pip

deploy:
  provider: pypi
  user: __token__
  password:
    secure: YtWaTWufwF2MiAf0ERqNKqfaC3FaWIlkT8P2g/vFu3GsywwseYM20+xmj6WafWbl1h45hLjTmpZoVO6XUX11I+t7VqOQ7mRdNGcuS65FMHS5OEvKWaaCahOdrKOL0jn8akNq/MdJTo5ZbGQABzWjAlon4hnawYSGJYRe4zolWCxQ628j1XspKO4MlJdQcWawQfWnqXHFswIccLvTBeoiMUoajiJpuNCIFGodMzAYyMUJlVgd+XvKaR4EH76T1bslDvV+9LYRdlowaWTcifn0C0UiZoJ/u1OrZTOTd0RtXPbLTgnwUygTQSzlfBHV4eG0vVOOVcDvggrwykzMURykRIIZEyRJupBuSvtAvxJN4B85AffIKls/8YxcGqU2xgxYwn1YPHQcDk7efTgQbOElrtIKbiyxZUtSnunTEWgmzAinIMMffOjVPTJPA78RLWozk04UqVBBM4aFOVHHmKkosl4r6gEpljPtaX0/NCr+QMka6ThBsCLbNxfUsm/H8BcNJGtQWZ+GMcnxF4UostsY3rVG6QkgNaIytCkzi2fwB04pIwZ/muvxDkkprf9Ao2cM97DChiYirQuUyS+89xUb5SJByB/i6MpOqsND7QP8kFSbQM/huvAqlKbx1Z8py2Nnqpe/JsUwCGsyUqOy+DvXI/fkL7Tsq24YDDqkBhubaSw=
  distributions: 'sdist bdist_wheel'
  on:
    tags: true

script:
  - pip install flake8
  - flake8 substra
  - pip install -e .[test]
  - python setup.py test
  - python bin/generate_cli_documentation.py --output-path references/cli.md.tmp
  - cmp --silent references/cli.md references/cli.md.tmp
  - pydocmd simple substra.sdk+ substra.sdk.Client+ > references/sdk.md.tmp
  - cmp --silent references/sdk.md references/sdk.md.tmp
